export const PLATFORMS = {
  twitter: {
    name: "X (Twitter)",
    maxChars: 280,
    icon: "twitter",
    characterLimit: 280,
    optimalLength: "250–280",
    hashtagTip: "Use 1–3 relevant hashtags; more can reduce reach.",
    bestPractice: "Hook in the first line; use line breaks for readability.",
  },
  threads: {
    name: "Threads",
    maxChars: 500,
    icon: "at-sign",
    characterLimit: 500,
    optimalLength: "400–500",
    hashtagTip: "Hashtags work but are less dominant than on X.",
    bestPractice: "Conversational tone; threads work well for stories.",
  },
  reddit: {
    name: "Reddit",
    maxChars: 10000,
    icon: "message-square",
    characterLimit: 10000,
    optimalLength: "200–500 for comments",
    hashtagTip: "Reddit uses subreddits, not hashtags.",
    bestPractice: "Use markdown (**bold**, *italic*); add TL;DR for long posts.",
  },
  mastodon: {
    name: "Mastodon",
    maxChars: 500,
    icon: "hash",
    characterLimit: 500,
    optimalLength: "400–500",
    hashtagTip: "Hashtags help with discoverability across instances.",
    bestPractice: "Use content warnings (CW) for sensitive topics.",
  },
  linkedin: {
    name: "LinkedIn",
    maxChars: 3000,
    icon: "linkedin",
    characterLimit: 3000,
    optimalLength: "150–300 for engagement",
    hashtagTip: "3–5 professional hashtags; avoid over-tagging.",
    bestPractice: "Professional tone; hook in first line; use line breaks.",
  },
  facebook: {
    name: "Facebook",
    maxChars: 63206,
    icon: "facebook",
    characterLimit: 63206,
    optimalLength: "40–80 for best engagement",
    hashtagTip: "1–2 hashtags; Facebook is less hashtag-driven.",
    bestPractice: "Short posts or clear structure; use paragraphs for long content.",
  },
}

export type PlatformKey = keyof typeof PLATFORMS
